#!/bin/bash
#set -ev

[[ "$SkipProcessing" == "yes" ]] && exit 0

if [ ! -z $jiraticket ] 
then 
  premsg="$jiraticket #comment [skip ci] "
else
  premsg="[skip ci] "
fi

if [ ! -d generated ]
then
  mkdir generated
fi

# Check if generated/dot-gitignore exists and commit it separately
if [ -f generated/dot-gitignore ]; then
  # Check if there are actual differences
  if ! diff -q .gitignore generated/dot-gitignore > /dev/null 2>&1; then
    echo "Updating .gitignore with auto-generated large file exclusions..."
    cp generated/dot-gitignore .gitignore
    git add .gitignore

    # Create commit message explaining the change
    commit_msg="Auto-update .gitignore to exclude large files

This commit updates .gitignore based on automated file size checks.
Files larger than the configured limit have been added to prevent
accidental commits of large files to the repository.

Generated by: automations/01_check_file_sizes.sh"

    git commit -m "${commit_msg}" .gitignore | tee generated/git-commit-gitignore.log

    case ${PIPESTATUS[0]} in
      0)
      echo ".gitignore updated and committed successfully"
      ;;
      1)
      echo "No changes to .gitignore detected"
      ;;
    esac
  else
    echo "generated/dot-gitignore exists but is identical to .gitignore, skipping"
  fi
fi

flag=$2

case $flag in
   run)
   gitmsg="Attempted run $(date +%Y-%m-%d:%H:%M)"
   ;;
   *)
   gitmsg="Adding code from $1"
   ;;
esac

if [ ! -z $1 ] 
then 
  git add -v $1
  git commit -m "${premsg}$gitmsg" $1 | tee generated/git-commit.log
  case ${PIPESTATUS[0]} in
     0)
     echo "Files added"
     # count the number of previous tags
     if [ "$flag" == "" ]
     then
      #tags=$(git tag | grep -E "^update" | wc -l)
      # counting them is not reliable, as Bitbucket Pipelines only clones the last 50 commits
      # extract the tag number
      tags=$(git tag | grep -E "^update" | sort | tail -1)
      tags=$(echo $tags | sed 's/update//')
      # now increase counter
      tags=$(expr $tags + 1)
      echo "This is code update $tags"
      git tag -m "Code added from ICPSR" update$tags | tee -a generated/git-commit.log
      echo "Code tagged"
      exit 0
     fi
     ;;
     1)
     echo "No changes detected"
     ;;
     *)
     echo "Not sure how we got here"
     ;;
  esac
fi

exit 0
