#!/usr/bin/env python3
"""Keep the "run from the Bitbucket pipeline" header in docs/automations/ in sync.

Every script in automations/ has a doc page in docs/automations/ that carries
the MyST label (help-<script stem>)=, e.g. (help-00_unpack_zip)= for
automations/00_unpack_zip.sh. Right below the page's H1 title, this tool
writes an admonition saying that the script is normally run by a Bitbucket
pipeline, with links to every place that calls it:

- each line of bitbucket-pipelines.yml that calls the script, linked to the
  pipeline's section in docs/automations/96-92-bitbucket-pipelines.md (label
  (pipeline-<name>)=) and to the line on GitHub;
- each line of another automations/*.sh script that calls it.

The block sits between BEGIN/END marker comments and is rewritten on every
run, so line numbers stay current. Run it after editing bitbucket-pipelines.yml
or an automation script, or after adding a doc page:

    python3 tools/automation_doc_links.py           # rewrite the blocks
    python3 tools/automation_doc_links.py --check   # exit 1 if anything is stale or missing
"""
import argparse
import glob
import os
import re
import sys
from collections import OrderedDict

GITHUB_BASE = "https://github.com/AEADataEditor/replication-template/blob/master"
PIPELINES_YML = "bitbucket-pipelines.yml"
PIPELINES_DOC = os.path.join("docs", "automations", "96-92-bitbucket-pipelines.md")
DOCS_DIR = os.path.join("docs", "automations")
BEGIN = "<!-- BEGIN pipeline-callers: generated by tools/automation_doc_links.py, do not edit by hand -->"
END = "<!-- END pipeline-callers -->"

SCRIPT_RE = re.compile(r"automations/(\d\d_[A-Za-z0-9_.-]+\.sh)")
# A call inside a shell script: the line starts with the command, optionally
# behind "if", "if !", "bash" or "." (source). Mentions in echo/usage text don't match.
SHELL_CALL_RE = re.compile(r"^\s*(?:if\s+!?\s*)?(?:bash\s+|\.\s+)?(?:\./)?automations/(\d\d_[A-Za-z0-9_.-]+\.sh)")
LABEL_RE = re.compile(r"^\(help-(\d\d_[A-Za-z0-9_.-]+)\)=\s*$", re.MULTILINE)


def scan_pipelines(path):
    """Return {script: [(pipeline, step, anchor, lineno)]} for calls in bitbucket-pipelines.yml.

    Calls inside a shared step definition (``- step: &anchor``) are attributed
    to every pipeline that pulls the anchor in with ``<<: *anchor``.
    """
    calls = {}
    anchor_calls = {}   # anchor -> [(script, lineno)]
    anchor_users = {}   # anchor -> [(pipeline, step name)]
    section = None
    pipeline = None
    step = None
    anchor = None
    want_step_name = False
    pending_anchor_use = None
    with open(path, encoding="utf-8") as fh:
        lines = fh.read().splitlines()
    for lineno, line in enumerate(lines, start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        top = re.match(r"^([A-Za-z_-]+):", line)
        if top:
            section = top.group(1)
            continue
        if section == "pipelines":
            if re.match(r"^  [A-Za-z_-]+:", line):
                pipeline = None
                continue
            m = re.match(r"^    ([A-Za-z0-9_-]+):", line)
            if m:
                pipeline, step, anchor = m.group(1), None, None
                continue
        m = re.match(r"^\s*- step:\s*(?:&(\S+))?", line)
        if m:
            anchor = m.group(1) if section == "definitions" else None
            step, want_step_name, pending_anchor_use = None, True, None
            continue
        m = re.match(r"^\s*<<:\s*\*(\S+)", line)
        if m and section == "pipelines":
            pending_anchor_use = m.group(1)
            continue
        m = re.match(r"^\s*name:\s*(.+?)\s*$", line)
        if m and want_step_name:
            step, want_step_name = m.group(1), False
            if pending_anchor_use and pipeline:
                anchor_users.setdefault(pending_anchor_use, []).append((pipeline, step))
            continue
        for script in SCRIPT_RE.findall(line):
            if section == "definitions" and anchor:
                anchor_calls.setdefault(anchor, []).append((script, lineno))
            elif section == "pipelines" and pipeline:
                calls.setdefault(script, []).append((pipeline, step, None, lineno))
    for anc, used in anchor_calls.items():
        for script, lineno in used:
            for pipe, step_name in anchor_users.get(anc, []):
                calls.setdefault(script, []).append((pipe, step_name, anc, lineno))
    return calls


def scan_scripts(root):
    """Return {script: [(caller script, lineno)]} for calls between automations/*.sh."""
    calls = {}
    for path in sorted(glob.glob(os.path.join(root, "automations", "*.sh"))):
        caller = os.path.basename(path)
        with open(path, encoding="utf-8") as fh:
            for lineno, line in enumerate(fh, start=1):
                m = SHELL_CALL_RE.match(line)
                if m and m.group(1) != caller:
                    calls.setdefault(m.group(1), []).append((caller, lineno))
    return calls


def find_doc_pages(root):
    """Return {script: doc path} for pages in docs/automations/ with a (help-<stem>)= label."""
    pages = {}
    for path in sorted(glob.glob(os.path.join(root, DOCS_DIR, "*.md"))):
        with open(path, encoding="utf-8") as fh:
            for stem in LABEL_RE.findall(fh.read()):
                pages[stem + ".sh"] = path
    return pages


def render_block(script, pipeline_calls, script_calls, documented):
    """Return the admonition block (with markers) for one script."""
    yml_url = f"{GITHUB_BASE}/{PIPELINES_YML}"
    out = [BEGIN]
    if pipeline_calls:
        out.append(":::{attention} Usually run by a Bitbucket pipeline")
        out.append(f"`{script}` is normally not run on its own. The Bitbucket pipelines listed below call it "
                   "as one step of a longer job, after earlier steps have prepared its inputs and environment. "
                   "Run it by hand mainly for debugging or local testing.")
    elif script_calls:
        out.append(":::{attention} Usually run by another automation script")
        out.append(f"`{script}` is normally not run on its own. The automation scripts listed below call it, "
                   "and they are in turn run by the Bitbucket pipelines. "
                   "Run it by hand mainly for debugging or local testing.")
    else:
        out.append(":::{attention} Not currently called by any pipeline")
        out.append(f"No Bitbucket pipeline and no other automation script calls `{script}` at present. "
                   "It is kept for manual use; check that it still works before relying on it.")
    if pipeline_calls:
        out += ["", f"**Called from [bitbucket-pipelines.yml]({yml_url}):**", ""]
        grouped = OrderedDict()
        for pipeline, step, anchor, lineno in pipeline_calls:
            grouped.setdefault((pipeline, step, anchor), []).append(lineno)
        for (pipeline, step, anchor), linenos in grouped.items():
            where = f"[`{pipeline}`](#pipeline-{pipeline})"
            if step:
                where += f', step "{step}"'
            if anchor:
                where += f" (shared step definition `{anchor}`)"
            links = ", ".join(f"[line {n}]({yml_url}#L{n})" for n in linenos)
            out.append(f"- {where}: {links}")
    if script_calls:
        out += ["", "**Called from other automation scripts:**", ""]
        grouped = OrderedDict()
        for caller, lineno in script_calls:
            grouped.setdefault(caller, []).append(lineno)
        for caller, linenos in grouped.items():
            name = f"[`{caller}`](#help-{caller[:-3]})" if caller in documented else f"`{caller}`"
            links = ", ".join(f"[line {n}]({GITHUB_BASE}/automations/{caller}#L{n})" for n in linenos)
            out.append(f"- {name}: {links}")
    out += [":::", END]
    return "\n".join(out)


def apply_block(text, block):
    """Replace the marked block in text, or insert it after the first H1 heading."""
    if BEGIN in text and END in text:
        start = text.index(BEGIN)
        stop = text.index(END) + len(END)
        return text[:start] + block + text[stop:]
    m = re.search(r"^# .*$", text, re.MULTILINE)
    if not m:
        raise ValueError("no H1 heading to insert the block after")
    return text[:m.end()] + "\n\n" + block + text[m.end():]


def run(root, check):
    problems = []
    pipeline_calls = scan_pipelines(os.path.join(root, PIPELINES_YML))
    script_calls = scan_scripts(root)
    pages = find_doc_pages(root)
    scripts = sorted(os.path.basename(p) for p in glob.glob(os.path.join(root, "automations", "*.sh")))

    with open(os.path.join(root, PIPELINES_DOC), encoding="utf-8") as fh:
        pipelines_doc = fh.read()
    for pipeline in sorted({c[0] for calls in pipeline_calls.values() for c in calls}):
        if f"(pipeline-{pipeline})=" not in pipelines_doc:
            problems.append(f"{PIPELINES_DOC}: missing label (pipeline-{pipeline})= for pipeline {pipeline}")

    changed = []
    for script in scripts:
        page = pages.get(script)
        if not page:
            problems.append(f"automations/{script}: no page in {DOCS_DIR}/ with label (help-{script[:-3]})=")
            continue
        block = render_block(script, pipeline_calls.get(script, []), script_calls.get(script, []), pages)
        with open(page, encoding="utf-8") as fh:
            text = fh.read()
        try:
            new = apply_block(text, block)
        except ValueError as err:
            problems.append(f"{page}: {err}")
            continue
        if new != text:
            changed.append(page)
            if not check:
                with open(page, "w", encoding="utf-8") as fh:
                    fh.write(new)

    for page in changed:
        print(f"{'stale' if check else 'updated'}: {os.path.relpath(page, root)}")
    for problem in problems:
        print(f"ERROR: {problem}", file=sys.stderr)
    if problems or (check and changed):
        return 1
    return 0


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true",
                        help="only report stale or missing pages; exit 1 if there are any")
    parser.add_argument("--root", default=os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                        help="repository root (default: parent of tools/)")
    args = parser.parse_args(argv)
    return run(args.root, args.check)


if __name__ == "__main__":
    sys.exit(main())
