#!/bin/bash
# This does the same as bitbucket-pipelines.yml, Download step.
# Should be auto-generated by a tool.

openICPSRID=$1
force=$2

# read functions

[ -f ./tools/parse_yaml.sh ] && source ./tools/parse_yaml.sh


if [[ -z $openICPSRID ]]
then
  if [[ -f config.yml ]]
  then
    # lets read it
    echo "--------------------------------"
    cat config.yml
    echo "--------------------------------"
    tmpfile=$(mktemp)
    parse_yaml config.yml > $tmpfile
    source $tmpfile
  fi
fi


projectID=$openICPSRID

echo "Note: this works on Github CS, not guaranteed in other contexts"
echo "Requirements: Python 3.8, stata-mp"
echo "projectID=$projectID : Ready? y/N"

if [[ -z $force ]]
then
  read answer
else
  answer="y"
fi
case $answer in
   y|Y)
     echo "OK, you asked for it"
     ;;
   *)
   exit 0
   ;;
esac

./automations/00_prepare_aux.sh 
./automations/01_check_files_sizes.sh $projectID
./automations/02_list_data_files.sh $projectID
./automations/03_list_program_files.sh $projectID
./automations/04_create_manifest.sh $projectID
./automations/05_count_lines.sh $projectID
./automations/06_check_duplicates_and_zero_bytes.sh $projectID
./automations/07_file_paths.sh $projectID
./automations/10_run_stata_scanner.sh $projectID
./automations/14_run_r_scanner.sh $projectID
./automations/15_run_python_scanner.sh $projectID
./automations/16_run_pii_scanner.sh $openICPSRID
./automations/17_run_julia_scanner.sh $openICPSRID


./automations/24_amend_report.sh 

./automations/20_commit_code.sh $projectID
./automations/21_cleanup.sh $projectID
./automations/25_replace_report.sh 
./automations/30_cleanup_aux.sh 
