#!/bin/bash
# This does the same as bitbucket-pipelines.yml, Download step.
# Should be auto-generated by a tool.

openICPSRID=$1

# read functions

[ -f ./tools/parse_yaml.sh ] && source ./tools/parse_yaml.sh

if [[ -z $openICPSRID ]]
then
  if [[ -f config.yml ]]
  then
    # lets read it
    echo "--------------------------------"
    cat config.yml
    echo "--------------------------------"
    tmpfile=$(mktemp)
    parse_yaml config.yml > $tmpfile
    source $tmpfile
  fi
fi

echo "Ready? y/N"
read answer
case $answer in
   y|Y)
     echo "OK, you asked for it"
     ;;
   *)
   exit 0
   ;;
esac

if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
if [ -d $openICPSRID ]; then 
	echo "\rm -rf $openICPSRID"
        echo " Do this yourself! "
	exit 2
fi
if [ -f tools/download_openicpsr-private.py ]; then python3 tools/download_openicpsr-private.py $openICPSRID; fi
mkdir cache
mv *.zip cache/
chmod a+rx ./automations/*.sh
./automations/01_prepare_aux.sh
./automations/02_list_data_files.sh $openICPSRID
./automations/03_list_program_files.sh $openICPSRID
./automations/04_create_manifest.sh $openICPSRID
ls -lR
